// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: proto/spot/v1/spot.proto

package v1

import (
	common "exchange-system/proto/common"
	v1 "exchange-system/proto/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Market represents a tradable instrument pair (base/quote currency)
type Market struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MarketId       string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Symbol         string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseCurrency   string                 `protobuf:"bytes,3,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency  string                 `protobuf:"bytes,4,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	Enabled        bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MinOrderSize   string                 `protobuf:"bytes,6,opt,name=min_order_size,json=minOrderSize,proto3" json:"min_order_size,omitempty"`
	MaxOrderSize   string                 `protobuf:"bytes,7,opt,name=max_order_size,json=maxOrderSize,proto3" json:"max_order_size,omitempty"`
	PriceIncrement string                 `protobuf:"bytes,8,opt,name=price_increment,json=priceIncrement,proto3" json:"price_increment,omitempty"`
	SizeIncrement  string                 `protobuf:"bytes,9,opt,name=size_increment,json=sizeIncrement,proto3" json:"size_increment,omitempty"`
	// ✅ Стандартный Timestamp вместо int64
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_proto_spot_v1_spot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spot_v1_spot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_proto_spot_v1_spot_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Market) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Market) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *Market) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

func (x *Market) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Market) GetMinOrderSize() string {
	if x != nil {
		return x.MinOrderSize
	}
	return ""
}

func (x *Market) GetMaxOrderSize() string {
	if x != nil {
		return x.MaxOrderSize
	}
	return ""
}

func (x *Market) GetPriceIncrement() string {
	if x != nil {
		return x.PriceIncrement
	}
	return ""
}

func (x *Market) GetSizeIncrement() string {
	if x != nil {
		return x.SizeIncrement
	}
	return ""
}

func (x *Market) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Market) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Market) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ViewMarketsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ✅ RBAC: фильтрация по ролям
	UserRoles []v1.UserRole `protobuf:"varint,1,rep,packed,name=user_roles,json=userRoles,proto3,enum=user.v1.UserRole" json:"user_roles,omitempty"`
	// ✅ Курсорная пагинация из common
	Pagination    *common.CursorPaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_proto_spot_v1_spot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spot_v1_spot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_spot_v1_spot_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsRequest) GetUserRoles() []v1.UserRole {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *ViewMarketsRequest) GetPagination() *common.CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ViewMarketsResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Markets       []*Market                        `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	Pagination    *common.CursorPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_proto_spot_v1_spot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spot_v1_spot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_spot_v1_spot_proto_rawDescGZIP(), []int{2}
}

func (x *ViewMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *ViewMarketsResponse) GetPagination() *common.CursorPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketRequest) Reset() {
	*x = GetMarketRequest{}
	mi := &file_proto_spot_v1_spot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketRequest) ProtoMessage() {}

func (x *GetMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spot_v1_spot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketRequest.ProtoReflect.Descriptor instead.
func (*GetMarketRequest) Descriptor() ([]byte, []int) {
	return file_proto_spot_v1_spot_proto_rawDescGZIP(), []int{3}
}

func (x *GetMarketRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type GetMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *Market                `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketResponse) Reset() {
	*x = GetMarketResponse{}
	mi := &file_proto_spot_v1_spot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketResponse) ProtoMessage() {}

func (x *GetMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spot_v1_spot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketResponse.ProtoReflect.Descriptor instead.
func (*GetMarketResponse) Descriptor() ([]byte, []int) {
	return file_proto_spot_v1_spot_proto_rawDescGZIP(), []int{4}
}

func (x *GetMarketResponse) GetMarket() *Market {
	if x != nil {
		return x.Market
	}
	return nil
}

var File_proto_spot_v1_spot_proto protoreflect.FileDescriptor

const file_proto_spot_v1_spot_proto_rawDesc = "" +
	"\n" +
	"\x18proto/spot/v1/spot.proto\x12\aspot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19proto/common/common.proto\x1a\x18proto/user/v1/user.proto\"\xf0\x03\n" +
	"\x06Market\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12#\n" +
	"\rbase_currency\x18\x03 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0equote_currency\x18\x04 \x01(\tR\rquoteCurrency\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12$\n" +
	"\x0emin_order_size\x18\x06 \x01(\tR\fminOrderSize\x12$\n" +
	"\x0emax_order_size\x18\a \x01(\tR\fmaxOrderSize\x12'\n" +
	"\x0fprice_increment\x18\b \x01(\tR\x0epriceIncrement\x12%\n" +
	"\x0esize_increment\x18\t \x01(\tR\rsizeIncrement\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x87\x01\n" +
	"\x12ViewMarketsRequest\x120\n" +
	"\n" +
	"user_roles\x18\x01 \x03(\x0e2\x11.user.v1.UserRoleR\tuserRoles\x12?\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1f.common.CursorPaginationRequestR\n" +
	"pagination\"\x82\x01\n" +
	"\x13ViewMarketsResponse\x12)\n" +
	"\amarkets\x18\x01 \x03(\v2\x0f.spot.v1.MarketR\amarkets\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .common.CursorPaginationResponseR\n" +
	"pagination\"/\n" +
	"\x10GetMarketRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"<\n" +
	"\x11GetMarketResponse\x12'\n" +
	"\x06market\x18\x01 \x01(\v2\x0f.spot.v1.MarketR\x06market2\xa5\x01\n" +
	"\x15SpotInstrumentService\x12H\n" +
	"\vViewMarkets\x12\x1b.spot.v1.ViewMarketsRequest\x1a\x1c.spot.v1.ViewMarketsResponse\x12B\n" +
	"\tGetMarket\x12\x19.spot.v1.GetMarketRequest\x1a\x1a.spot.v1.GetMarketResponseB\x1fZ\x1dexchange-system/proto/spot/v1b\x06proto3"

var (
	file_proto_spot_v1_spot_proto_rawDescOnce sync.Once
	file_proto_spot_v1_spot_proto_rawDescData []byte
)

func file_proto_spot_v1_spot_proto_rawDescGZIP() []byte {
	file_proto_spot_v1_spot_proto_rawDescOnce.Do(func() {
		file_proto_spot_v1_spot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_spot_v1_spot_proto_rawDesc), len(file_proto_spot_v1_spot_proto_rawDesc)))
	})
	return file_proto_spot_v1_spot_proto_rawDescData
}

var file_proto_spot_v1_spot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_spot_v1_spot_proto_goTypes = []any{
	(*Market)(nil),                          // 0: spot.v1.Market
	(*ViewMarketsRequest)(nil),              // 1: spot.v1.ViewMarketsRequest
	(*ViewMarketsResponse)(nil),             // 2: spot.v1.ViewMarketsResponse
	(*GetMarketRequest)(nil),                // 3: spot.v1.GetMarketRequest
	(*GetMarketResponse)(nil),               // 4: spot.v1.GetMarketResponse
	(*timestamppb.Timestamp)(nil),           // 5: google.protobuf.Timestamp
	(v1.UserRole)(0),                        // 6: user.v1.UserRole
	(*common.CursorPaginationRequest)(nil),  // 7: common.CursorPaginationRequest
	(*common.CursorPaginationResponse)(nil), // 8: common.CursorPaginationResponse
}
var file_proto_spot_v1_spot_proto_depIdxs = []int32{
	5,  // 0: spot.v1.Market.created_at:type_name -> google.protobuf.Timestamp
	5,  // 1: spot.v1.Market.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 2: spot.v1.Market.deleted_at:type_name -> google.protobuf.Timestamp
	6,  // 3: spot.v1.ViewMarketsRequest.user_roles:type_name -> user.v1.UserRole
	7,  // 4: spot.v1.ViewMarketsRequest.pagination:type_name -> common.CursorPaginationRequest
	0,  // 5: spot.v1.ViewMarketsResponse.markets:type_name -> spot.v1.Market
	8,  // 6: spot.v1.ViewMarketsResponse.pagination:type_name -> common.CursorPaginationResponse
	0,  // 7: spot.v1.GetMarketResponse.market:type_name -> spot.v1.Market
	1,  // 8: spot.v1.SpotInstrumentService.ViewMarkets:input_type -> spot.v1.ViewMarketsRequest
	3,  // 9: spot.v1.SpotInstrumentService.GetMarket:input_type -> spot.v1.GetMarketRequest
	2,  // 10: spot.v1.SpotInstrumentService.ViewMarkets:output_type -> spot.v1.ViewMarketsResponse
	4,  // 11: spot.v1.SpotInstrumentService.GetMarket:output_type -> spot.v1.GetMarketResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_spot_v1_spot_proto_init() }
func file_proto_spot_v1_spot_proto_init() {
	if File_proto_spot_v1_spot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_spot_v1_spot_proto_rawDesc), len(file_proto_spot_v1_spot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_spot_v1_spot_proto_goTypes,
		DependencyIndexes: file_proto_spot_v1_spot_proto_depIdxs,
		MessageInfos:      file_proto_spot_v1_spot_proto_msgTypes,
	}.Build()
	File_proto_spot_v1_spot_proto = out.File
	file_proto_spot_v1_spot_proto_goTypes = nil
	file_proto_spot_v1_spot_proto_depIdxs = nil
}
